# Generated by Django 4.1.7 on 2023-03-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmodel",
            name="slug",
            field=models.SlugField(
                max_length=150, null=True, unique=True, verbose_name="слаг"
            ),
        ),
    ]
