# Generated by Django 4.1.7 on 2023-03-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0002_bookmodel_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmodel",
            options={
                "get_latest_by": "publication_date",
                "ordering": ["title"],
                "verbose_name": "книга",
                "verbose_name_plural": "книги",
            },
        ),
        migrations.AddField(
            model_name="bookmodel",
            name="publication_date",
            field=models.DateField(
                default="2023-01-01", verbose_name="дата публикации"
            ),
            preserve_default=False,
        ),
    ]
